server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: invoice-app

discounts:
  employee:
    percentage: 30
    priority: 1
  affiliate:
    percentage: 10
    priority: 1
  customer:
    percentage: 5
    priority: 1
    registeredYears: 2
